/* Generated By:JavaCC: Do not edit this line. WordParserConstants.java */
package it.gov.scuolesuperioridizagarolo.parser.impl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WordParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BLANK_MULTIPLI = 5;
  /** RegularExpression Id. */
  int SEPARATORE = 6;
  /** RegularExpression Id. */
  int NUMBER_1_2cifre = 7;
  /** RegularExpression Id. */
  int NUMBER_2cifre = 8;
  /** RegularExpression Id. */
  int MESE = 9;
  /** RegularExpression Id. */
  int NUMBER_4cifre = 10;
  /** RegularExpression Id. */
  int TEMPLATE_DATA = 11;
  /** RegularExpression Id. */
  int DATA = 12;
  /** RegularExpression Id. */
  int CLASSE = 13;
  /** RegularExpression Id. */
  int NUMERO = 14;
  /** RegularExpression Id. */
  int TELEFONO = 15;
  /** RegularExpression Id. */
  int CIRCOLARE = 16;
  /** RegularExpression Id. */
  int NUMERO_PUNTATO = 17;
  /** RegularExpression Id. */
  int AVVISO = 18;
  /** RegularExpression Id. */
  int EMAIL = 19;
  /** RegularExpression Id. */
  int PAROLA = 20;
  /** RegularExpression Id. */
  int ALTRO = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<BLANK_MULTIPLI>",
    "<SEPARATORE>",
    "<NUMBER_1_2cifre>",
    "<NUMBER_2cifre>",
    "<MESE>",
    "<NUMBER_4cifre>",
    "<TEMPLATE_DATA>",
    "<DATA>",
    "<CLASSE>",
    "<NUMERO>",
    "<TELEFONO>",
    "\"Circolare\"",
    "<NUMERO_PUNTATO>",
    "\"avviso\"",
    "<EMAIL>",
    "<PAROLA>",
    "<ALTRO>",
  };

}
