/* Generated By:JavaCC: Do not edit this line. WordParserConstants.java */
package it.gov.scuolesuperioridizagarolo.parser.impl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WordParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BLANK_MULTIPLI = 15;
  /** RegularExpression Id. */
  int SEPARATORE = 16;
  /** RegularExpression Id. */
  int NUMBER_1_2cifre = 17;
  /** RegularExpression Id. */
  int NUMBER_2cifre = 18;
  /** RegularExpression Id. */
  int MESE = 19;
  /** RegularExpression Id. */
  int NUMBER_4cifre = 20;
  /** RegularExpression Id. */
  int TEMPLATE_DATA = 21;
  /** RegularExpression Id. */
  int DATA = 22;
  /** RegularExpression Id. */
  int CLASSE = 23;
  /** RegularExpression Id. */
  int NUMERO = 24;
  /** RegularExpression Id. */
  int TELEFONO = 25;
  /** RegularExpression Id. */
  int CIRCOLARE = 26;
  /** RegularExpression Id. */
  int EMAIL = 27;
  /** RegularExpression Id. */
  int PAROLA = 28;
  /** RegularExpression Id. */
  int ALTRO = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\".\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"-\"",
    "\"!\"",
    "\"\\\"\"",
    "\"?\"",
    "\"\\\'\"",
    "\"^\"",
    "<BLANK_MULTIPLI>",
    "<SEPARATORE>",
    "<NUMBER_1_2cifre>",
    "<NUMBER_2cifre>",
    "<MESE>",
    "<NUMBER_4cifre>",
    "<TEMPLATE_DATA>",
    "<DATA>",
    "<CLASSE>",
    "<NUMERO>",
    "<TELEFONO>",
    "<CIRCOLARE>",
    "<EMAIL>",
    "<PAROLA>",
    "<ALTRO>",
  };

}
