package it.gov.scuolesuperioridizagarolo2.backoffice.cotral;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.*;

/**
 * Created by stefano on 31/05/15.
 */
public class MainCotral {
    public static void main(String[] args) {
        Set<String> fermate = new TreeSet<String>();
        fermate.add("Abbadia San Salvatore");
        fermate.add("Acquafondata");
        fermate.add("Acquaforte (VT) (Celleno)");
        fermate.add("Acquapendente");
        fermate.add("Acuto");
        fermate.add("Aeroporto di Fiumicino");
        fermate.add("Affile");
        fermate.add("Agosta");
        fermate.add("Alatri");
        fermate.add("Albano Laziale");
        fermate.add("Allumiere");
        fermate.add("Altip. Arcinazzo (FR) (Trevi nel Lazio)");
        fermate.add("Alvito");
        fermate.add("Amaseno");
        fermate.add("Amatrice");
        fermate.add("Anagni");
        fermate.add("Anagni (Comune)");
        fermate.add("Anguillara Sabazia");
        fermate.add("Anticoli - Roviano bv");
        fermate.add("Anticoli Corrado");
        fermate.add("Antrodoco");
        fermate.add("Anzio");
        fermate.add("Aprilia");
        fermate.add("Aquapiper (Guidonia Montecelio)");
        fermate.add("Aquino");
        fermate.add("Arce");
        fermate.add("Arcinazzo Romano");
        fermate.add("Ardea");
        fermate.add("Ariccia (Comune)");
        fermate.add("Arlena di Castro");
        fermate.add("Arnara");
        fermate.add("Arpino");
        fermate.add("Arsoli");
        fermate.add("Artena");
        fermate.add("Artena (Comune)");
        fermate.add("Ascrea");
        fermate.add("Atina");
        fermate.add("Ausonia");
        fermate.add("Ausonia (Comune)");
        fermate.add("Avezzano");
        fermate.add("Bagnoregio");
        fermate.add("Barbarano Romano");
        fermate.add("Bassano Romano");
        fermate.add("Bassano in Teverina");
        fermate.add("Bassiano");
        fermate.add("Bellegra");
        fermate.add("Belmonte Castello");
        fermate.add("Belmonte in Sabina");
        fermate.add("Blera");
        fermate.add("Bolsena");
        fermate.add("Bomarzo");
        fermate.add("Borbona");
        fermate.add("Borghesiana (Roma)");
        fermate.add("Borgo Hermada (Terracina)");
        fermate.add("Borgo Montenero (San Felice Circeo)");
        fermate.add("Borgo Velino");
        fermate.add("Borgo Vodice (Sabaudia)");
        fermate.add("Borgorose");
        fermate.add("Boville Ernica");
        fermate.add("Bracciano");
        fermate.add("Broccostella");
        fermate.add("Calcata");
        fermate.add("Calvi dell'Umbria");
        fermate.add("Camerata Nuova");
        fermate.add("Campagnano di Roma");
        fermate.add("Campo Ascolano (Pomezia)");
        fermate.add("Campo dell'Osso (Subiaco)");
        fermate.add("Campodimele");
        fermate.add("Campoli Appennino");
        fermate.add("Canale Monterano");
        fermate.add("Canepina");
        fermate.add("Canino");
        fermate.add("Cantalice");
        fermate.add("Cantalupo in Sabina");
        fermate.add("Cantalupo in Sabina (Comune)");
        fermate.add("Canterano");
        fermate.add("Capacqua (Poggio Mirteto)");
        fermate.add("Capena");
        fermate.add("Capodimonte");
        fermate.add("Cappelle (Scurcola Marsicana)");
        fermate.add("Capranica");
        fermate.add("Capranica Prenestina");
        fermate.add("Capranica-Scalo");
        fermate.add("Caprarola");
        fermate.add("Carbognano");
        fermate.add("Carchitti (Palestrina)");
        fermate.add("Caronti (Ardea)");
        fermate.add("Carpineto Romano");
        fermate.add("Carsoli");
        fermate.add("Casalattico");
        fermate.add("Casalvieri");
        fermate.add("Casamari (Veroli)");
        fermate.add("Casape");
        fermate.add("Casaprota");
        fermate.add("Cascia");
        fermate.add("Casperia");
        fermate.add("Casperia (Comune)");
        fermate.add("Cassino");
        fermate.add("Castel Cellesi (Bagnoregio)");
        fermate.add("Castel Gandolfo");
        fermate.add("Castel Giorgio");
        fermate.add("Castel Madama");
        fermate.add("Castel San Pietro Romano");
        fermate.add("Castel Sant'Angelo");
        fermate.add("Castel Sant'Angelo Stazione FS");
        fermate.add("Castel Sant'Elia");
        fermate.add("Castel Viscardo");
        fermate.add("Castel di Tora");
        fermate.add("Castelforte (Comune)");
        fermate.add("Castelliri");
        fermate.add("Castelnuovo Parano");
        fermate.add("Castelnuovo di Farfa");
        fermate.add("Castelnuovo di Porto");
        fermate.add("Castiglione in Teverina");
        fermate.add("Castro dei Volsci Stazione FS");
        fermate.add("Castrocielo");
        fermate.add("Cave");
        fermate.add("Ceccano");
        fermate.add("Cecchina (Albano Laziale)");
        fermate.add("Celleno");
        fermate.add("Cellere");
        fermate.add("Ceprano");
        fermate.add("Ceprano FS");
        fermate.add("Cerquotti-Madonna del Piano (Morolo)");
        fermate.add("Cerreto Laziale");
        fermate.add("Cervara di Roma");
        fermate.add("Cervaro");
        fermate.add("Cerveteri");
        fermate.add("Chia (Soriano nel Cimino)");
        fermate.add("Chiesa Nuova (Sora)");
        fermate.add("Ciampino");
        fermate.add("Ciciliano");
        fermate.add("Cineto Romano");
        fermate.add("Cisterna di Latina");
        fermate.add("Cittaducale");
        fermate.add("Civita Castellana");
        fermate.add("Civita Prima (Oricola)");
        fermate.add("Civitavecchia");
        fermate.add("Civitella San Paolo");
        fermate.add("Civitella d'Agliano");
        fermate.add("Collalto Sabino");
        fermate.add("Colle San Magno");
        fermate.add("Colle di Tora");
        fermate.add("Colleferro");
        fermate.add("Colleferro IPIA");
        fermate.add("Colleferro Scalo");
        fermate.add("Collegiove");
        fermate.add("Collepardo");
        fermate.add("Collevecchio");
        fermate.add("Collevecchio Scalo");
        fermate.add("Colli sul Velino");
        fermate.add("Colonna");
        fermate.add("Colonna Bivio (San Cesareo)");
        fermate.add("Commenda (Montefiascone)");
        fermate.add("Concerviano");
        fermate.add("Contigliano");
        fermate.add("Corchiano");
        fermate.add("Coreno Ausonio");
        fermate.add("Cori");
        fermate.add("Correano (Ausonia)");
        fermate.add("Cotilia (Castel Sant'Angelo)");
        fermate.add("Cottanello");
        fermate.add("Esperia");
        fermate.add("Fabrica di Roma");
        fermate.add("Faleria");
        fermate.add("Falvaterra");
        fermate.add("Fara in Sabina");
        fermate.add("Farnese");
        fermate.add("Ferentino");
        fermate.add("Fiamignano");
        fermate.add("Fiano Romano");
        fermate.add("Fiano Romano (Comune)");
        fermate.add("Filacciano");
        fermate.add("Filettino");
        fermate.add("Finocchio (Roma)");
        fermate.add("Fiuggi");
        fermate.add("Fiumata (Petrella Salto)");
        fermate.add("Fiumicino");
        fermate.add("Fondi");
        fermate.add("Fontana Liri");
        fermate.add("Fonte Nuova");
        fermate.add("Fontechiari");
        fermate.add("Forano");
        fermate.add("Formello");
        fermate.add("Formello (Comune)");
        fermate.add("Formia");
        fermate.add("Frascati");
        fermate.add("Frasso Sabino");
        fermate.add("Fregene (Fiumicino)");
        fermate.add("Frosinone");
        fermate.add("Fumone");
        fermate.add("Gaeta");
        fermate.add("Gallese");
        fermate.add("Gallese Teverina FS");
        fermate.add("Gallicano nel Lazio");
        fermate.add("Gallinaro");
        fermate.add("Gavignano");
        fermate.add("Gavignano Sabino (Forano)");
        fermate.add("Genazzano");
        fermate.add("Genzano di Roma");
        fermate.add("Gerano");
        fermate.add("Gignano (L'Aquila)");
        fermate.add("Giuliano di Roma");
        fermate.add("Gorga");
        fermate.add("Gradoli");
        fermate.add("Graffignano");
        fermate.add("Greccio");
        fermate.add("Grottaferrata");
        fermate.add("Grotte Celoni (Roma)");
        fermate.add("Grotte Santo Stefano (Viterbo)");
        fermate.add("Grotte di Castro");
        fermate.add("Guadagnolo (Capranica Prenestina)");
        fermate.add("Guarcino");
        fermate.add("Guidonia Montecelio");
        fermate.add("I Terzi (Cerveteri)");
        fermate.add("Ischia di Castro");
        fermate.add("Isola Sacra (Fiumicino)");
        fermate.add("Isola del Liri");
        fermate.add("Itri");
        fermate.add("Jenne");
        fermate.add("La Macchia (Vico nel Lazio)");
        fermate.add("Labico");
        fermate.add("Labro");
        fermate.add("Ladispoli");
        fermate.add("Lanuvio");
        fermate.add("Lariano");
        fermate.add("Latera");
        fermate.add("Latina");
        fermate.add("Latina Scalo FS");
        fermate.add("Lenola");
        fermate.add("Lenola (Comune)");
        fermate.add("Leonessa");
        fermate.add("Licenza");
        fermate.add("Lido di Ostia (Roma)");
        fermate.add("Livata (Subiaco)");
        fermate.add("Longone Sabino (Comune)");
        fermate.add("Lubriano");
        fermate.add("Maccarese (Fiumicino)");
        fermate.add("Madonna del Piano (Castro dei Volsci)");
        fermate.add("Maenza");
        fermate.add("Magliano Romano");
        fermate.add("Magliano Sabina");
        fermate.add("Magliano de' Marsi");
        fermate.add("Manciano");
        fermate.add("Mandela");
        fermate.add("Mandela Scalo Stazione (Vicovaro)");
        fermate.add("Manziana");
        fermate.add("Marano Equo");
        fermate.add("Marcellina");
        fermate.add("Marcetelli");
        fermate.add("Marco Simone (Guidonia Montecelio)");
        fermate.add("Marina di Palidoro (Fiumicino)");
        fermate.add("Marino");
        fermate.add("Marta");
        fermate.add("Mazzano Romano");
        fermate.add("Mentana");
        fermate.add("Micigliano");
        fermate.add("Minturno");
        fermate.add("Minturno FS");
        fermate.add("Mompeo");
        fermate.add("Montalto Marina (Montalto di Castro)");
        fermate.add("Montalto di Castro");
        fermate.add("Montasola");
        fermate.add("Monte Compatri");
        fermate.add("Monte Porzio Catone");
        fermate.add("Monte Romano");
        fermate.add("Monte S.Biagio");
        fermate.add("Monte San Giovanni Campano");
        fermate.add("Monte San Giovanni in Sabina");
        fermate.add("Montebello (RM) (Roma)");
        fermate.add("Montebuono");
        fermate.add("Montecelio (Guidonia Montecelio)");
        fermate.add("Montefiascone");
        fermate.add("Monteflavio");
        fermate.add("Montelanico");
        fermate.add("Monteleone Sabino");
        fermate.add("Montelibretti");
        fermate.add("Montenero Sabino");
        fermate.add("Monterosi");
        fermate.add("Monterotondo");
        fermate.add("Montopoli di Sabina");
        fermate.add("Montorio Romano");
        fermate.add("Morena (Roma)");
        fermate.add("Moricone");
        fermate.add("Morlupo");
        fermate.add("Morlupo (Comune)");
        fermate.add("Morolo");
        fermate.add("Morro Reatino");
        fermate.add("Mugnano (VT) (Bomarzo)");
        fermate.add("Nazzano");
        fermate.add("Nemi");
        fermate.add("Nepi");
        fermate.add("Nerola");
        fermate.add("Nespolo");
        fermate.add("Nettuno");
        fermate.add("Ninfa (Norma)");
        fermate.add("Norma");
        fermate.add("Olevano Romano");
        fermate.add("Onano");
        fermate.add("Oriolo Romano");
        fermate.add("Orte");
        fermate.add("Orte Scalo");
        fermate.add("Orvieto");
        fermate.add("Orvieto Scalo");
        fermate.add("Orvinio");
        fermate.add("Osteria Configni");
        fermate.add("Paganico Sabino");
        fermate.add("Palestrina");
        fermate.add("Paliano");
        fermate.add("Pallottini (Cittareale)");
        fermate.add("Palombara Sabina");
        fermate.add("Passo Corese (Fara in Sabina)");
        fermate.add("Passo Oscuro (Fiumicino)");
        fermate.add("Pastena");
        fermate.add("Patrica");
        fermate.add("Percile");
        fermate.add("Pescia Romana (Montalto di Castro)");
        fermate.add("Pescorocchiano");
        fermate.add("Pescosolido");
        fermate.add("Petrella Salto");
        fermate.add("Piancastagnaio");
        fermate.add("Piansano");
        fermate.add("Picinisco");
        fermate.add("Pico");
        fermate.add("Piedimonte San Germano");
        fermate.add("Piedimonte San Germano FS");
        fermate.add("Piglio");
        fermate.add("Pignataro Interamna");
        fermate.add("Pisoniano");
        fermate.add("Pofi");
        fermate.add("Poggio Bustone");
        fermate.add("Poggio Catino");
        fermate.add("Poggio Mirteto");
        fermate.add("Poggio Mirteto (Comune)");
        fermate.add("Poggio Mirteto Scalo");
        fermate.add("Poggio Moiano");
        fermate.add("Poggio Nativo");
        fermate.add("Poggio San Lorenzo");
        fermate.add("Poli");
        fermate.add("Pomezia");
        fermate.add("Pontecorvo");
        fermate.add("Pontinia");
        fermate.add("Ponzano Primare (Ponzano Romano)");
        fermate.add("Ponzano Romano");
        fermate.add("Porano");
        fermate.add("Posta");
        fermate.add("Posta Fibreno");
        fermate.add("Pozzaglia Sabina");
        fermate.add("Pratica di Mare (Pomezia)");
        fermate.add("Priverno");
        fermate.add("Proceno");
        fermate.add("Prossedi");
        fermate.add("Riano");
        fermate.add("Rieti");
        fermate.add("Rignano Flaminio");
        fermate.add("Riofreddo");
        fermate.add("Riofreddo Bivio");
        fermate.add("Ripi");
        fermate.add("Rivodutri");
        fermate.add("Rocca Canterano");
        fermate.add("Rocca Massima");
        fermate.add("Rocca Priora");
        fermate.add("Rocca Santo Stefano");
        fermate.add("Rocca Sinibalda");
        fermate.add("Rocca d'Arce");
        fermate.add("Rocca d'Evandro");
        fermate.add("Rocca di Botte");
        fermate.add("Rocca di Cave");
        fermate.add("Rocca di Mezzo");
        fermate.add("Rocca di Papa");
        fermate.add("Rocca di Papa (Comune)");
        fermate.add("Roccagiovine");
        fermate.add("Roccagorga");
        fermate.add("Roccantica");
        fermate.add("Roccasecca");
        fermate.add("Roccasecca Stazione FS");
        fermate.add("Roccasecca dei Volsci");
        fermate.add("Roiate");
        fermate.add("Roma (Comune)");
        fermate.add("Roma Anagnina [Metro A]");
        fermate.add("Roma Cipro Musei Vaticani [Metro A]");
        fermate.add("Roma Cornelia [Metro A]");
        fermate.add("Roma Eur Magliana [Metro B]");
        fermate.add("Roma Laurentina [Metro B]");
        fermate.add("Roma Ponte Mammolo [Metro B]");
        fermate.add("Roma Saxa Rubra");
        fermate.add("Roma Termini [Staz.FS - Metro A-B]");
        fermate.add("Roma Tiburtina [Staz.FS - Metro B]");
        fermate.add("Ronciglione");
        fermate.add("Roviano");
        fermate.add("S.Maria delle Mole (Marino)");
        fermate.add("S.Michele Teverina (Civitella d'Agliano)");
        fermate.add("Sabaudia");
        fermate.add("Sacrofano");
        fermate.add("Sacrofano Stazione (Roma)");
        fermate.add("Salisano");
        fermate.add("Sambuci");
        fermate.add("San Biagio Saracinisco");
        fermate.add("San Cesareo");
        fermate.add("San Domenico (Sora)");
        fermate.add("San Donato Val di Comino");
        fermate.add("San Felice Circeo");
        fermate.add("San Francesco (Bellegra)");
        fermate.add("San Giorgio a Liri");
        fermate.add("San Giovanni Incarico");
        fermate.add("San Gregorio da Sassola");
        fermate.add("San Lorenzo Nuovo");
        fermate.add("San Pietro Infine");
        fermate.add("San Polo dei Cavalieri");
        fermate.add("San Vito Romano");
        fermate.add("San Vittore del Lazio");
        fermate.add("Sant'Ambrogio sul Garigliano");
        fermate.add("Sant'Andrea del Garigliano");
        fermate.add("Sant'Angelo Romano");
        fermate.add("Sant'Apollinare");
        fermate.add("Sant'Elia Fiumerapido");
        fermate.add("Sant'Oreste");
        fermate.add("Santa Lucia di Fonte Nuova");
        fermate.add("Santa Marinella");
        fermate.add("Santa Severa (Santa Marinella)");
        fermate.add("Santi Cosma e Damiano (Comune)");
        fermate.add("Santopadre");
        fermate.add("Saracinesco");
        fermate.add("Scandriglia");
        fermate.add("Scauri (Minturno)");
        fermate.add("Segni");
        fermate.add("Selci");
        fermate.add("Sermoneta");
        fermate.add("Serrone");
        fermate.add("Setteville (Guidonia Montecelio)");
        fermate.add("Sezze");
        fermate.add("Sezze Scalo");
        fermate.add("Sgurgola");
        fermate.add("Sigillo");
        fermate.add("Simonelli (Minturno)");
        fermate.add("Sonnino");
        fermate.add("Sora");
        fermate.add("Soriano nel Cimino");
        fermate.add("Sperlonga");
        fermate.add("Spigno Saturnia");
        fermate.add("Spigno Saturnia Sup.");
        fermate.add("Staz.Magliano Romano (Morlupo)");
        fermate.add("Stazione Fossanova (Priverno)");
        fermate.add("Stazione Sant'Oreste");
        fermate.add("Stazione di Anagni");
        fermate.add("Stazione di Cesano (Roma)");
        fermate.add("Stimigliano");
        fermate.add("Stimigliano Scalo");
        fermate.add("Strangolagalli");
        fermate.add("Subiaco");
        fermate.add("Suio Terme (Castelforte)");
        fermate.add("Supino");
        fermate.add("Sutri");
        fermate.add("Tarano");
        fermate.add("Tarquinia");
        fermate.add("Terelle");
        fermate.add("Terme di Viterbo");
        fermate.add("Terni");
        fermate.add("Terracina");
        fermate.add("Tessennano");
        fermate.add("Testa di Lepre (Fiumicino)");
        fermate.add("Tivoli");
        fermate.add("Toffia");
        fermate.add("Tolfa");
        fermate.add("Tor S.Lorenzo (Ardea)");
        fermate.add("Tor Vergata FS (Frascati)");
        fermate.add("Torre Alfina (Acquapendente)");
        fermate.add("Torre Cajetani");
        fermate.add("Torre Mancina (Monterotondo)");
        fermate.add("Torri in Sabina");
        fermate.add("Torrice");
        fermate.add("Torricella in Sabina");
        fermate.add("Torrita Tiberina");
        fermate.add("Torvaianica (Pomezia)");
        fermate.add("Trevi nel Lazio");
        fermate.add("Trevignano Romano");
        fermate.add("Trevinano (Acquapendente)");
        fermate.add("Trivigliano");
        fermate.add("Turania");
        fermate.add("Tuscania");
        fermate.add("Vacone");
        fermate.add("Valentano");
        fermate.add("Valle Martella (Zagarolo)");
        fermate.add("Vallecorsa");
        fermate.add("Vallemaio");
        fermate.add("Vallepietra");
        fermate.add("Vallerano");
        fermate.add("Vallerotonda");
        fermate.add("Vallinfreda");
        fermate.add("Valmontone");
        fermate.add("Valvori (Vallerotonda)");
        fermate.add("Varco Sabino");
        fermate.add("Vasanello");
        fermate.add("Vejano");
        fermate.add("Velletri");
        fermate.add("Velletri (Comune)");
        fermate.add("Veroli");
        fermate.add("Vetralla");
        fermate.add("Vicalvi");
        fermate.add("Vicovaro");
        fermate.add("Vignanello");
        fermate.add("Vignola (Anagni)");
        fermate.add("Villa Adriana (Tivoli)");
        fermate.add("Villa Felice (Colfelice)");
        fermate.add("Villa Latina");
        fermate.add("Villa San Giovanni in Tuscia");
        fermate.add("Villa Santa Lucia");
        fermate.add("Villa Santo Stefano");
        fermate.add("Villalba (Guidonia Montecelio)");
        fermate.add("Viterbo");
        fermate.add("Viticuso");
        fermate.add("Vitorchiano");
        fermate.add("Vitorchiano Stazione");
        fermate.add("Vivaro Romano");
        fermate.add("XII Apostoli (Fonte Nuova)");
        fermate.add("Zagarolo");
        fermate.add("Zagarolo FS");
        fermate.add("Zepponami FS (Montefiascone)");
        fermate.add("Zona Industriale (Anagni)");
        fermate.add("Zona Industriale (Ferentino)");
        fermate.add("Zona Industriale (Piedimonte San Germano)");
        fermate.add("staz.Ferentino-Supino");

        Map<String, String> m = new TreeMap<String, String>();
        m.put("Abbadia San Salvatore", "22081002");
        m.put("Acquafondata", "22035001");
        m.put("Acquapendente", "22102001");
        m.put("Acuto", "22035002");
        m.put("Affile", "22079002");
        m.put("Agosta", "22079003");
        m.put("Alatri", "22035003");
        m.put("Albano Laziale", "22079004");
        m.put("Allumiere", "22079005");
        m.put("Alvito", "22035004");
        m.put("Amaseno", "22035005");
        m.put("Amatrice", "22076003");
        m.put("Anagni", "22035006");
        m.put("Anguillara Sabazia", "22079007");
        m.put("Anticoli Corrado", "22079008");
        m.put("Antrodoco", "22076004");
        m.put("Anzio", "22079009");
        m.put("Aprilia", "22046003");
        m.put("Aquino", "22035008");
        m.put("Arce", "22035009");
        m.put("Arcinazzo Romano", "22079011");
        m.put("Ardea", "22079012");
        m.put("Ariccia", "22079013");
        m.put("Arlena di Castro", "22102002");
        m.put("Arnara", "22035010");
        m.put("Arpino", "22035011");
        m.put("Arsoli", "22079015");
        m.put("Artena", "22079016");
        m.put("Ascrea", "22076006");
        m.put("Atina", "22035012");
        m.put("Ausonia", "22035013");
        m.put("Avezzano", "22006017");
        m.put("Bagnoregio", "22102004");
        m.put("Barbarano Romano", "22102005");
        m.put("Bassano Romano", "22102007");
        m.put("Bassano in Teverina", "22102006");
        m.put("Bassiano", "22046006");
        m.put("Bellegra", "22079019");
        m.put("Belmonte Castello", "22035014");
        m.put("Belmonte in Sabina", "22076007");
        m.put("Blera", "22102008");
        m.put("Bolsena", "22102009");
        m.put("Bomarzo", "22102010");
        m.put("Borbona", "22076009");
        m.put("Borgo Velino", "22076013");
        m.put("Borgorose", "22076014");
        m.put("Boville Ernica", "22035015");
        m.put("Bracciano", "22079021");
        m.put("Broccostella", "22035017");
        m.put("Calcata", "22102012");
        m.put("Calvi dell'Umbria", "22092013");
        m.put("Camerata Nuova", "22079022");
        m.put("Campagnano di Roma", "22079023");
        m.put("Campodimele", "22046025");
        m.put("Campoli Appennino", "22035020");
        m.put("Canale Monterano", "22079025");
        m.put("Canepina", "22102013");
        m.put("Canino", "22102014");
        m.put("Cantalice", "22076018");
        m.put("Cantalupo in Sabina", "22076019");
        m.put("Canterano", "22079026");
        m.put("Capena", "22079027");
        m.put("Capodimonte", "22102015");
        m.put("Capranica", "22102016");
        m.put("Capranica Prenestina", "22079028");
        m.put("Caprarola", "22102017");
        m.put("Carbognano", "22102018");
        m.put("Carpineto Romano", "22079029");
        m.put("Carsoli", "22006047");
        m.put("Casalattico", "22035024");
        m.put("Casalvieri", "22035026");
        m.put("Casape", "22079032");
        m.put("Casaprota", "22076021");
        m.put("Cascia", "22063041");
        m.put("Casperia", "22076023");
        m.put("Cassino", "22035029");
        m.put("Castel Gandolfo", "22079034");
        m.put("Castel Giorgio", "22092019");
        m.put("Castel Madama", "22079036");
        m.put("Castel San Pietro Romano", "22079037");
        m.put("Castel Sant'Angelo", "22076025");
        m.put("Castel Sant'Elia", "22102021");
        m.put("Castel Viscardo", "22092020");
        m.put("Castel di Tora", "22076024");
        m.put("Castelforte", "22046030");
        m.put("Castelliri", "22035030");
        m.put("Castelnuovo Parano", "22035033");
        m.put("Castelnuovo di Farfa", "22076028");
        m.put("Castelnuovo di Porto", "22079040");
        m.put("Castiglione in Teverina", "22102022");
        m.put("Castro dei Volsci", "22035034");
        m.put("Castrocielo", "22035035");
        m.put("Cave", "22079042");
        m.put("Ceccano", "22035036");
        m.put("Celleno", "22102023");
        m.put("Cellere", "22102024");
        m.put("Ceprano", "22035037");
        m.put("Cerreto Laziale", "22079046");
        m.put("Cervara di Roma", "22079047");
        m.put("Cervaro", "22035040");
        m.put("Cerveteri", "22079048");
        m.put("Ciampino", "22079051");
        m.put("Ciciliano", "22079053");
        m.put("Cineto Romano", "22079054");
        m.put("Cisterna di Latina", "22046032");
        m.put("Cittaducale", "22076030");
        m.put("Cittareale", "22076031");
        m.put("Civita Castellana", "22102027");
        m.put("Civitavecchia", "22079055");
        m.put("Civitella San Paolo", "22079057");
        m.put("Civitella d'Agliano", "22102030");
        m.put("Colfelice", "22035042");
        m.put("Collalto Sabino", "22076032");
        m.put("Colle San Magno", "22035043");
        m.put("Colle di Tora", "22076033");
        m.put("Colleferro", "22079059");
        m.put("Collegiove", "22076034");
        m.put("Collepardo", "22035046");
        m.put("Collevecchio", "22076038");
        m.put("Colli sul Velino", "22076039");
        m.put("Colonna", "22079062");
        m.put("Concerviano", "22076041");
        m.put("Configni", "22076042");
        m.put("Contigliano", "22076043");
        m.put("Corchiano", "22102031");
        m.put("Coreno Ausonio", "22035048");
        m.put("Cori", "22046034");
        m.put("Cottanello", "22076046");
        m.put("Esperia", "22035049");
        m.put("Fabrica di Roma", "22102033");
        m.put("Faleria", "22102034");
        m.put("Falvaterra", "22035051");
        m.put("Fara in Sabina", "22076047");
        m.put("Farnese", "22102035");
        m.put("Ferentino", "22035052");
        m.put("Fiamignano", "22076051");
        m.put("Fiano Romano", "22079067");
        m.put("Filacciano", "22079068");
        m.put("Filettino", "22035053");
        m.put("Fiuggi", "22035054");
        m.put("Fiumicino", "22079070");
        m.put("Fondi", "22046038");
        m.put("Fontana Liri", "22035056");
        m.put("Fonte Nuova", "22079203");
        m.put("Fontechiari", "22035058");
        m.put("Forano", "22076055");
        m.put("Formello", "22079073");
        m.put("Formia", "22046039");
        m.put("Frascati", "22079074");
        m.put("Frasso Sabino", "22076056");
        m.put("Frosinone", "22035059");
        m.put("Fumone", "22035060");
        m.put("Gaeta", "22046041");
        m.put("Gallese", "22102037");
        m.put("Gallicano nel Lazio", "22079078");
        m.put("Gallinaro", "22035061");
        m.put("Gavignano", "22079080");
        m.put("Genazzano", "22079081");
        m.put("Genzano di Roma", "22079082");
        m.put("Gerano", "22079083");
        m.put("Giuliano di Roma", "22035063");
        m.put("Gorga", "22079084");
        m.put("Gradoli", "22102040");
        m.put("Graffignano", "22102041");
        m.put("Greccio", "22076059");
        m.put("Grottaferrata", "22079085");
        m.put("Grotte di Castro", "22102042");
        m.put("Guarcino", "22035064");
        m.put("Guidonia Montecelio", "22079087");
        m.put("Ischia di Castro", "22102044");
        m.put("Isola del Liri", "22035065");
        m.put("Itri", "22046044");
        m.put("Jenne", "22079089");
        m.put("L'Aquila", "22006092");
        m.put("Labico", "22079090");
        m.put("Labro", "22076063");
        m.put("Ladispoli", "22079091");
        m.put("Lanuvio", "22079094");
        m.put("Lariano", "22079095");
        m.put("Latera", "22102048");
        m.put("Latina", "22046047");
        m.put("Lenola", "22046052");
        m.put("Leonessa", "22076065");
        m.put("Licenza", "22079097");
        m.put("Longone Sabino", "22076067");
        m.put("Lubriano", "22102051");
        m.put("Maenza", "22046053");
        m.put("Magliano Romano", "22079104");
        m.put("Magliano Sabina", "22076068");
        m.put("Magliano de' Marsi", "22006096");
        m.put("Manciano", "22038054");
        m.put("Mandela", "22079106");
        m.put("Manziana", "22079107");
        m.put("Marano Equo", "22079108");
        m.put("Marcellina", "22079109");
        m.put("Marcetelli", "22076069");
        m.put("Marino", "22079110");
        m.put("Marta", "22102053");
        m.put("Mazzano Romano", "22079111");
        m.put("Mentana", "22079112");
        m.put("Micigliano", "22076070");
        m.put("Minturno", "22046056");
        m.put("Mompeo", "22076071");
        m.put("Montalto di Castro", "22102054");
        m.put("Montasola", "22076072");
        m.put("Monte Compatri", "22079115");
        m.put("Monte Porzio Catone", "22079113");
        m.put("Monte Romano", "22102055");
        m.put("Monte S.Biagio", "22046057");
        m.put("Monte San Giovanni Campano", "22035069");
        m.put("Monte San Giovanni in Sabina", "22076073");
        m.put("Montebuono", "22076076");
        m.put("Montefiascone", "22102056");
        m.put("Monteflavio", "22079116");
        m.put("Montelanico", "22079117");
        m.put("Monteleone Sabino", "22076077");
        m.put("Montelibretti", "22079118");
        m.put("Montenero Sabino", "22076078");
        m.put("Monterosi", "22102057");
        m.put("Monterotondo", "22079119");
        m.put("Montopoli di Sabina", "22076080");
        m.put("Montorio Romano", "22079122");
        m.put("Moricone", "22079124");
        m.put("Morlupo", "22079125");
        m.put("Morolo", "22035072");
        m.put("Morro Reatino", "22076081");
        m.put("Narni", "22092056");
        m.put("Nazzano", "22079126");
        m.put("Nemi", "22079127");
        m.put("Nepi", "22102060");
        m.put("Nerola", "22079128");
        m.put("Nespolo", "22076082");
        m.put("Nettuno", "22079129");
        m.put("Norma", "22046059");
        m.put("Olevano Romano", "22079130");
        m.put("Onano", "22102061");
        m.put("Oricola", "22006114");
        m.put("Oriolo Romano", "22102062");
        m.put("Orte", "22102063");
        m.put("Orvieto", "22092059");
        m.put("Orvinio", "22076083");
        m.put("Otricoli", "22092062");
        m.put("Paganico Sabino", "22076086");
        m.put("Palestrina", "22079131");
        m.put("Paliano", "22035074");
        m.put("Palombara Sabina", "22079133");
        m.put("Pastena", "22035075");
        m.put("Patrica", "22035077");
        m.put("Percile", "22079137");
        m.put("Pescorocchiano", "22076089");
        m.put("Pescosolido", "22035078");
        m.put("Petrella Salto", "22076090");
        m.put("Piancastagnaio", "22081072");
        m.put("Piansano", "22102066");
        m.put("Picinisco", "22035079");
        m.put("Pico", "22035080");
        m.put("Piedimonte San Germano", "22035081");
        m.put("Piglio", "22035083");
        m.put("Pignataro Interamna", "22035084");
        m.put("Pisoniano", "22079138");
        m.put("Pofi", "22035086");
        m.put("Poggio Bustone", "22076094");
        m.put("Poggio Catino", "22076095");
        m.put("Poggio Mirteto", "22076097");
        m.put("Poggio Moiano", "22076099");
        m.put("Poggio Nativo", "22076100");
        m.put("Poggio San Lorenzo", "22076102");
        m.put("Poli", "22079140");
        m.put("Pomezia", "22079141");
        m.put("Pontecorvo", "22035087");
        m.put("Pontinia", "22046062");
        m.put("Ponzano Romano", "22079145");
        m.put("Porano", "22092071");
        m.put("Posta", "22076105");
        m.put("Posta Fibreno", "22035090");
        m.put("Pozzaglia Sabina", "22076107");
        m.put("Priverno", "22046064");
        m.put("Proceno", "22102067");
        m.put("Prossedi", "22046065");
        m.put("Riano", "22079148");
        m.put("Rieti", "22076110");
        m.put("Rignano Flaminio", "22079149");
        m.put("Riofreddo", "22079150");
        m.put("Ripi", "22035092");
        m.put("Rivodutri", "22076111");
        m.put("Rocca Canterano", "22079151");
        m.put("Rocca Massima", "22046067");
        m.put("Rocca Priora", "22079154");
        m.put("Rocca Santo Stefano", "22079155");
        m.put("Rocca Sinibalda", "22076112");
        m.put("Rocca d'Arce", "22035093");
        m.put("Rocca d'Evandro", "22021137");
        m.put("Rocca di Botte", "22006150");
        m.put("Rocca di Cave", "22079152");
        m.put("Rocca di Mezzo", "22006152");
        m.put("Rocca di Papa", "22079153");
        m.put("Roccagiovine", "22079156");
        m.put("Roccagorga", "22046068");
        m.put("Roccantica", "22076113");
        m.put("Roccasecca", "22035094");
        m.put("Roccasecca dei Volsci", "22046069");
        m.put("Roiate", "22079157");
        m.put("Roma", "22079158");
        m.put("Ronciglione", "22102069");
        m.put("Roviano", "22079159");
        m.put("Sabaudia", "22046071");
        m.put("Sacrofano", "22079160");
        m.put("Salisano", "22076115");
        m.put("Sambuci", "22079162");
        m.put("San Biagio Saracinisco", "22035100");
        m.put("San Casciano dei Bagni", "22081092");
        m.put("San Cesareo", "22079163");
        m.put("San Donato Val di Comino", "22035101");
        m.put("San Felice Circeo", "22046070");
        m.put("San Giorgio a Liri", "22035102");
        m.put("San Giovanni Incarico", "22035103");
        m.put("San Gregorio da Sassola", "22079164");
        m.put("San Lorenzo Nuovo", "22102070");
        m.put("San Pietro Infine", "22102095");
        m.put("San Polo dei Cavalieri", "22079165");
        m.put("San Vito Romano", "22079166");
        m.put("San Vittore del Lazio", "22035104");
        m.put("Sant'Ambrogio sul Garigliano", "22035098");
        m.put("Sant'Andrea del Garigliano", "22035099");
        m.put("Sant'Angelo Romano", "22079167");
        m.put("Sant'Apollinare", "22035107");
        m.put("Sant'Elia Fiumerapido", "22035108");
        m.put("Sant'Oreste", "22079168");
        m.put("Santa Marinella", "22079171");
        m.put("Santi Cosma e Damiano", "22046076");
        m.put("Santopadre", "22035112");
        m.put("Saracinesco", "22079174");
        m.put("Scandriglia", "22076129");
        m.put("Scurcola Marsicana", "22006192");
        m.put("Segni", "22079175");
        m.put("Selci", "22076130");
        m.put("Sermoneta", "22046079");
        m.put("Serrone", "22035118");
        m.put("Settefrati", "22035119");
        m.put("Sezze", "22046080");
        m.put("Sgurgola", "22035120");
        m.put("Sigillo", "22063235");
        m.put("Sonnino", "22046082");
        m.put("Sora", "22035121");
        m.put("Soriano nel Cimino", "22102075");
        m.put("Sperlonga", "22046083");
        m.put("Spigno Saturnia", "22046084");
        m.put("Stimigliano", "22076133");
        m.put("Strangolagalli", "22035122");
        m.put("Subiaco", "22079177");
        m.put("Supino", "22035123");
        m.put("Sutri", "22102076");
        m.put("Tarano", "22076137");
        m.put("Tarquinia", "22102077");
        m.put("Terelle", "22035125");
        m.put("Terni", "22092095");
        m.put("Terracina", "22046086");
        m.put("Tessennano", "22102078");
        m.put("Tivoli", "22079180");
        m.put("Toffia", "22076139");
        m.put("Tolfa", "22079181");
        m.put("Torre Cajetani", "22035126");
        m.put("Torri in Sabina", "22076141");
        m.put("Torrice", "22035127");
        m.put("Torricella in Sabina", "22076142");
        m.put("Torrita Tiberina", "22079186");
        m.put("Trevi nel Lazio", "22035128");
        m.put("Trevignano Romano", "22079187");
        m.put("Trivigliano", "22035129");
        m.put("Turania", "22076144");
        m.put("Tuscania", "22102083");
        m.put("Vacone", "22076146");
        m.put("Valentano", "22102084");
        m.put("Vallecorsa", "22035130");
        m.put("Vallemaio", "22035132");
        m.put("Vallepietra", "22079189");
        m.put("Vallerano", "22102085");
        m.put("Vallerotonda", "22035133");
        m.put("Vallinfreda", "22079190");
        m.put("Valmontone", "22079191");
        m.put("Varco Sabino", "22076148");
        m.put("Vasanello", "22102086");
        m.put("Vejano", "22102087");
        m.put("Velletri", "22079192");
        m.put("Veroli", "22035135");
        m.put("Vetralla", "22102088");
        m.put("Vicalvi", "22035136");
        m.put("Vico nel Lazio", "22035137");
        m.put("Vicovaro", "22079195");
        m.put("Vignanello", "22102091");
        m.put("Villa Latina", "22035138");
        m.put("Villa San Giovanni in Tuscia", "22102092");
        m.put("Villa Santa Lucia", "22035139");
        m.put("Villa Santo Stefano", "22035140");
        m.put("Viterbo", "22102093");
        m.put("Viticuso", "22035141");
        m.put("Vitorchiano", "22102094");
        m.put("Vivaro Romano", "22079201");
        m.put("Zagarolo", "22079202");

        //cerca se ci sono citta' che non sono fermate
        for (String comune : m.keySet()) {
            if (!fermate.contains(comune))
                System.out.println("<item>"+comune+"</item>");


        }

        /*
        //cerca la citta' per ogni fermata
        for (String f : fermate) {
            boolean trovato = false;
            String comune = null;
            for (String s : m.keySet()) {
                if (f.contains(s)) {
                    trovato = true;
                    comune = s;
                    break;
                }
            }
            if (!trovato) {
                System.out.println(f);
            } else {
                System.out.println("<item>" + f.replace("'", "\\'") + "#" + comune.replace("'", "\\'") + "</item>");
            }

        }
        */
    }

    public static void main1(String[] args) throws IOException {
        TreeSet<String> s = new TreeSet<String>();
        s.addAll(getComuni("a"));
        s.addAll(getComuni("e"));
        s.addAll(getComuni("i"));
        s.addAll(getComuni("o"));
        s.addAll(getComuni("u"));


        for (String s1 : s) {
            System.out.println("m.put(" + s1 + ");");
        }
    }

    private static ArrayList<String> getComuni(String iniziale) throws IOException {
        String url = "http://www.cotralspa.it/Cotral_be.asmx/GetAutocompleteLocalitaPartenza4Orari";
        URL u = new URL(url);
        HttpURLConnection con = (HttpURLConnection) u.openConnection();
        con.setDoOutput(true);
        con.setDoInput(true);
        con.setRequestMethod("POST");

        //Connection: keep-alive
        //Content-Length: 23
        con.setRequestProperty("Accept", "application/json, text/javascript, */*; q=0.01");
        con.setRequestProperty("Origin", "http://www.cotralspa.it");
        con.setRequestProperty("X-Requested-With", "XMLHttpRequest");
        con.setRequestProperty("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36");
        con.setRequestProperty("Content-Type", "application/json; charset=UTF-8");
//Referer: http://www.cotralspa.it/Orari.aspx
        con.setRequestProperty("Accept-Encoding", "gzip, deflate");
        con.setRequestProperty("Accept-Language", "it,en-US;q=0.8,en;q=0.6");
//Cookie: _gat=1; _ga=GA1.2.1049016932.1433090740
        OutputStream o = con.getOutputStream();
        String data = "{ 'searchKey': '" + iniziale + "' }";
        o.write(data.getBytes());
        o.flush();

        con.connect();
        BufferedReader reader = new BufferedReader(new InputStreamReader(new BufferedInputStream(con.getInputStream())));
        String x = reader.readLine();

        //System.out.println(x);
        String[] split = x.split("\"");
        ArrayList<String> ris = new ArrayList<String>();
        for (String s : split) {
            s = s.trim();
            if (s.length() >= 3) {
                s = s.replace("\\u0027", "'");
                ris.add(s);
                //System.out.println(s);

            }
        }
        reader.close();
        return ris;
    }
}
