package it.gov.scuolesuperioridizagarolo.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ARTICOLO_DB".
 */
@Entity
public class ArticoloDB {

    @Id
    private Long id;
    private String title;
    private java.util.Date pubDate;
    private java.util.Date insertTimestamp;

    @Unique
    private Integer remoteId;
    private Integer remoteCategoryId;
    private String categoryTitle;
    private String content;
    private String url;

    @Generated
    public ArticoloDB() {
    }

    public ArticoloDB(Long id) {
        this.id = id;
    }

    @Generated
    public ArticoloDB(Long id, String title, java.util.Date pubDate, java.util.Date insertTimestamp, Integer remoteId, Integer remoteCategoryId, String categoryTitle, String content, String url) {
        this.id = id;
        this.title = title;
        this.pubDate = pubDate;
        this.insertTimestamp = insertTimestamp;
        this.remoteId = remoteId;
        this.remoteCategoryId = remoteCategoryId;
        this.categoryTitle = categoryTitle;
        this.content = content;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public java.util.Date getPubDate() {
        return pubDate;
    }

    public void setPubDate(java.util.Date pubDate) {
        this.pubDate = pubDate;
    }

    public java.util.Date getInsertTimestamp() {
        return insertTimestamp;
    }

    public void setInsertTimestamp(java.util.Date insertTimestamp) {
        this.insertTimestamp = insertTimestamp;
    }

    public Integer getRemoteId() {
        return remoteId;
    }

    public void setRemoteId(Integer remoteId) {
        this.remoteId = remoteId;
    }

    public Integer getRemoteCategoryId() {
        return remoteCategoryId;
    }

    public void setRemoteCategoryId(Integer remoteCategoryId) {
        this.remoteCategoryId = remoteCategoryId;
    }

    public String getCategoryTitle() {
        return categoryTitle;
    }

    public void setCategoryTitle(String categoryTitle) {
        this.categoryTitle = categoryTitle;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
