package it.gov.scuolesuperioridizagarolo.dao;

import org.greenrobot.greendao.DaoException;
import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ATTACHMENT_ARTICOLO_DB".
 */
@Entity(active = true)
public class AttachmentArticoloDB {

    @Id
    private Long id;

    @NotNull
    private String filename;

    @NotNull
    private String url;
    private int filesize;
    private int state;

    @NotNull
    private java.util.Date insertTimestamp;

    @NotNull
    private String filetype;

    @Index
    private long fk_articleId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient AttachmentArticoloDBDao myDao;

    @ToOne(joinProperty = "fk_articleId")
    private ArticoloDB articoloDB;

    @Generated
    private transient Long articoloDB__resolvedKey;

    @Generated
    public AttachmentArticoloDB() {
    }

    public AttachmentArticoloDB(Long id) {
        this.id = id;
    }

    @Generated
    public AttachmentArticoloDB(Long id, String filename, String url, int filesize, int state, java.util.Date insertTimestamp, String filetype, long fk_articleId) {
        this.id = id;
        this.filename = filename;
        this.url = url;
        this.filesize = filesize;
        this.state = state;
        this.insertTimestamp = insertTimestamp;
        this.filetype = filetype;
        this.fk_articleId = fk_articleId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getAttachmentArticoloDBDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getFilename() {
        return filename;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFilename(@NotNull String filename) {
        this.filename = filename;
    }

    @NotNull
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    public int getFilesize() {
        return filesize;
    }

    public void setFilesize(int filesize) {
        this.filesize = filesize;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    @NotNull
    public java.util.Date getInsertTimestamp() {
        return insertTimestamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInsertTimestamp(@NotNull java.util.Date insertTimestamp) {
        this.insertTimestamp = insertTimestamp;
    }

    @NotNull
    public String getFiletype() {
        return filetype;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFiletype(@NotNull String filetype) {
        this.filetype = filetype;
    }

    public long getFk_articleId() {
        return fk_articleId;
    }

    public void setFk_articleId(long fk_articleId) {
        this.fk_articleId = fk_articleId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public ArticoloDB getArticoloDB() {
        long __key = this.fk_articleId;
        if (articoloDB__resolvedKey == null || !articoloDB__resolvedKey.equals(__key)) {
            __throwIfDetached();
            ArticoloDBDao targetDao = daoSession.getArticoloDBDao();
            ArticoloDB articoloDBNew = targetDao.load(__key);
            synchronized (this) {
                articoloDB = articoloDBNew;
            	articoloDB__resolvedKey = __key;
            }
        }
        return articoloDB;
    }

    @Generated
    public void setArticoloDB(ArticoloDB articoloDB) {
        if (articoloDB == null) {
            throw new DaoException("To-one property 'fk_articleId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.articoloDB = articoloDB;
            fk_articleId = articoloDB.getId();
            articoloDB__resolvedKey = fk_articleId;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
