package it.gov.scuolesuperioridizagarolo.dao;

import org.greenrobot.greendao.annotation.*;

import it.gov.scuolesuperioridizagarolo.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CIRCOLARE_CONTIENE_TERMINE_DB".
 */
@Entity(active = true, indexes = {
    @Index(value = "_id_circolare, _id_termine", unique = true)
})
public class CircolareContieneTermineDB {
    private long _id_circolare;
    private long _id_termine;

    @Id(autoincrement = true)
    private Long id;
    private long occorrenze;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient CircolareContieneTermineDBDao myDao;

    @ToOne(joinProperty = "_id_circolare")
    private CircolareDB circolareDB;

    @Generated
    private transient Long circolareDB__resolvedKey;

    @ToOne(joinProperty = "_id_termine")
    private TermineDB termineDB;

    @Generated
    private transient Long termineDB__resolvedKey;

    @Generated
    public CircolareContieneTermineDB() {
    }

    public CircolareContieneTermineDB(Long id) {
        this.id = id;
    }

    @Generated
    public CircolareContieneTermineDB(long _id_circolare, long _id_termine, Long id, long occorrenze) {
        this._id_circolare = _id_circolare;
        this._id_termine = _id_termine;
        this.id = id;
        this.occorrenze = occorrenze;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCircolareContieneTermineDBDao() : null;
    }

    public long get_id_circolare() {
        return _id_circolare;
    }

    public void set_id_circolare(long _id_circolare) {
        this._id_circolare = _id_circolare;
    }

    public long get_id_termine() {
        return _id_termine;
    }

    public void set_id_termine(long _id_termine) {
        this._id_termine = _id_termine;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getOccorrenze() {
        return occorrenze;
    }

    public void setOccorrenze(long occorrenze) {
        this.occorrenze = occorrenze;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public CircolareDB getCircolareDB() {
        long __key = this._id_circolare;
        if (circolareDB__resolvedKey == null || !circolareDB__resolvedKey.equals(__key)) {
            __throwIfDetached();
            CircolareDBDao targetDao = daoSession.getCircolareDBDao();
            CircolareDB circolareDBNew = targetDao.load(__key);
            synchronized (this) {
                circolareDB = circolareDBNew;
            	circolareDB__resolvedKey = __key;
            }
        }
        return circolareDB;
    }

    @Generated
    public void setCircolareDB(CircolareDB circolareDB) {
        if (circolareDB == null) {
            throw new DaoException("To-one property '_id_circolare' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.circolareDB = circolareDB;
            _id_circolare = circolareDB.getId();
            circolareDB__resolvedKey = _id_circolare;
        }
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public TermineDB getTermineDB() {
        long __key = this._id_termine;
        if (termineDB__resolvedKey == null || !termineDB__resolvedKey.equals(__key)) {
            __throwIfDetached();
            TermineDBDao targetDao = daoSession.getTermineDBDao();
            TermineDB termineDBNew = targetDao.load(__key);
            synchronized (this) {
                termineDB = termineDBNew;
            	termineDB__resolvedKey = __key;
            }
        }
        return termineDB;
    }

    @Generated
    public void setTermineDB(TermineDB termineDB) {
        if (termineDB == null) {
            throw new DaoException("To-one property '_id_termine' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.termineDB = termineDB;
            _id_termine = termineDB.getId();
            termineDB__resolvedKey = _id_termine;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
