package it.gov.scuolesuperioridizagarolo.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CIRCOLARE_DB".
 */
@Entity(indexes = {
    @Index(value = "data, numero", unique = true)
})
public class CircolareDB {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private java.util.Date dataInserimento;

    @NotNull
    private java.util.Date data;
    private int numero;

    @NotNull
    private String titolo;
    private String testo;
    private long token;

    @NotNull
    @Unique
    private String url;
    private boolean flagContenutoLetto;

    @NotNull
    @Unique
    private String key;

    @Generated
    public CircolareDB() {
    }

    public CircolareDB(Long id) {
        this.id = id;
    }

    @Generated
    public CircolareDB(Long id, java.util.Date dataInserimento, java.util.Date data, int numero, String titolo, String testo, long token, String url, boolean flagContenutoLetto, String key) {
        this.id = id;
        this.dataInserimento = dataInserimento;
        this.data = data;
        this.numero = numero;
        this.titolo = titolo;
        this.testo = testo;
        this.token = token;
        this.url = url;
        this.flagContenutoLetto = flagContenutoLetto;
        this.key = key;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public java.util.Date getDataInserimento() {
        return dataInserimento;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDataInserimento(@NotNull java.util.Date dataInserimento) {
        this.dataInserimento = dataInserimento;
    }

    @NotNull
    public java.util.Date getData() {
        return data;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setData(@NotNull java.util.Date data) {
        this.data = data;
    }

    public int getNumero() {
        return numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    @NotNull
    public String getTitolo() {
        return titolo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitolo(@NotNull String titolo) {
        this.titolo = titolo;
    }

    public String getTesto() {
        return testo;
    }

    public void setTesto(String testo) {
        this.testo = testo;
    }

    public long getToken() {
        return token;
    }

    public void setToken(long token) {
        this.token = token;
    }

    @NotNull
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    public boolean getFlagContenutoLetto() {
        return flagContenutoLetto;
    }

    public void setFlagContenutoLetto(boolean flagContenutoLetto) {
        this.flagContenutoLetto = flagContenutoLetto;
    }

    @NotNull
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(@NotNull String key) {
        this.key = key;
    }

}
