package it.gov.scuolesuperioridizagarolo.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;
import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.internal.SqlUtils;

import java.util.ArrayList;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CIRCOLARE_CONTIENE_TERMINE_DB".
*/
public class CircolareContieneTermineDBDao extends AbstractDao<CircolareContieneTermineDB, Long> {

    public static final String TABLENAME = "CIRCOLARE_CONTIENE_TERMINE_DB";

    /**
     * Properties of entity CircolareContieneTermineDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id_circolare = new Property(0, long.class, "_id_circolare", false, "_ID_CIRCOLARE");
        public final static Property _id_termine = new Property(1, long.class, "_id_termine", false, "_ID_TERMINE");
        public final static Property Id = new Property(2, Long.class, "id", true, "_id");
        public final static Property Occorrenze = new Property(3, long.class, "occorrenze", false, "OCCORRENZE");
    }

    private DaoSession daoSession;


    public CircolareContieneTermineDBDao(DaoConfig config) {
        super(config);
    }
    
    public CircolareContieneTermineDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CIRCOLARE_CONTIENE_TERMINE_DB\" (" + //
                "\"_ID_CIRCOLARE\" INTEGER NOT NULL ," + // 0: _id_circolare
                "\"_ID_TERMINE\" INTEGER NOT NULL ," + // 1: _id_termine
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 2: id
                "\"OCCORRENZE\" INTEGER NOT NULL );"); // 3: occorrenze
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_CIRCOLARE_CONTIENE_TERMINE_DB__ID_CIRCOLARE__ID_TERMINE ON \"CIRCOLARE_CONTIENE_TERMINE_DB\"" +
                " (\"_ID_CIRCOLARE\",\"_ID_TERMINE\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CIRCOLARE_CONTIENE_TERMINE_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CircolareContieneTermineDB entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.get_id_circolare());
        stmt.bindLong(2, entity.get_id_termine());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(3, id);
        }
        stmt.bindLong(4, entity.getOccorrenze());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CircolareContieneTermineDB entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.get_id_circolare());
        stmt.bindLong(2, entity.get_id_termine());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(3, id);
        }
        stmt.bindLong(4, entity.getOccorrenze());
    }

    @Override
    protected final void attachEntity(CircolareContieneTermineDB entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2);
    }    

    @Override
    public CircolareContieneTermineDB readEntity(Cursor cursor, int offset) {
        CircolareContieneTermineDB entity = new CircolareContieneTermineDB( //
            cursor.getLong(offset + 0), // _id_circolare
            cursor.getLong(offset + 1), // _id_termine
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // id
            cursor.getLong(offset + 3) // occorrenze
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CircolareContieneTermineDB entity, int offset) {
        entity.set_id_circolare(cursor.getLong(offset + 0));
        entity.set_id_termine(cursor.getLong(offset + 1));
        entity.setId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setOccorrenze(cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CircolareContieneTermineDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CircolareContieneTermineDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CircolareContieneTermineDB entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCircolareDBDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getTermineDBDao().getAllColumns());
            builder.append(" FROM CIRCOLARE_CONTIENE_TERMINE_DB T");
            builder.append(" LEFT JOIN CIRCOLARE_DB T0 ON T.\"_ID_CIRCOLARE\"=T0.\"_id\"");
            builder.append(" LEFT JOIN TERMINE_DB T1 ON T.\"_ID_TERMINE\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected CircolareContieneTermineDB loadCurrentDeep(Cursor cursor, boolean lock) {
        CircolareContieneTermineDB entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CircolareDB circolareDB = loadCurrentOther(daoSession.getCircolareDBDao(), cursor, offset);
         if(circolareDB != null) {
            entity.setCircolareDB(circolareDB);
        }
        offset += daoSession.getCircolareDBDao().getAllColumns().length;

        TermineDB termineDB = loadCurrentOther(daoSession.getTermineDBDao(), cursor, offset);
         if(termineDB != null) {
            entity.setTermineDB(termineDB);
        }

        return entity;    
    }

    public CircolareContieneTermineDB loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<CircolareContieneTermineDB> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<CircolareContieneTermineDB> list = new ArrayList<CircolareContieneTermineDB>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<CircolareContieneTermineDB> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<CircolareContieneTermineDB> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
