package it.gov.scuolesuperioridizagarolo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import it.gov.scuolesuperioridizagarolo.dao.CacheFileDB;
import it.gov.scuolesuperioridizagarolo.dao.TimetableDB;
import it.gov.scuolesuperioridizagarolo.dao.ArticoloDB;
import it.gov.scuolesuperioridizagarolo.dao.TagArticoloDB;
import it.gov.scuolesuperioridizagarolo.dao.AttachmentArticoloDB;

import it.gov.scuolesuperioridizagarolo.dao.CacheFileDBDao;
import it.gov.scuolesuperioridizagarolo.dao.TimetableDBDao;
import it.gov.scuolesuperioridizagarolo.dao.ArticoloDBDao;
import it.gov.scuolesuperioridizagarolo.dao.TagArticoloDBDao;
import it.gov.scuolesuperioridizagarolo.dao.AttachmentArticoloDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheFileDBDaoConfig;
    private final DaoConfig timetableDBDaoConfig;
    private final DaoConfig articoloDBDaoConfig;
    private final DaoConfig tagArticoloDBDaoConfig;
    private final DaoConfig attachmentArticoloDBDaoConfig;

    private final CacheFileDBDao cacheFileDBDao;
    private final TimetableDBDao timetableDBDao;
    private final ArticoloDBDao articoloDBDao;
    private final TagArticoloDBDao tagArticoloDBDao;
    private final AttachmentArticoloDBDao attachmentArticoloDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheFileDBDaoConfig = daoConfigMap.get(CacheFileDBDao.class).clone();
        cacheFileDBDaoConfig.initIdentityScope(type);

        timetableDBDaoConfig = daoConfigMap.get(TimetableDBDao.class).clone();
        timetableDBDaoConfig.initIdentityScope(type);

        articoloDBDaoConfig = daoConfigMap.get(ArticoloDBDao.class).clone();
        articoloDBDaoConfig.initIdentityScope(type);

        tagArticoloDBDaoConfig = daoConfigMap.get(TagArticoloDBDao.class).clone();
        tagArticoloDBDaoConfig.initIdentityScope(type);

        attachmentArticoloDBDaoConfig = daoConfigMap.get(AttachmentArticoloDBDao.class).clone();
        attachmentArticoloDBDaoConfig.initIdentityScope(type);

        cacheFileDBDao = new CacheFileDBDao(cacheFileDBDaoConfig, this);
        timetableDBDao = new TimetableDBDao(timetableDBDaoConfig, this);
        articoloDBDao = new ArticoloDBDao(articoloDBDaoConfig, this);
        tagArticoloDBDao = new TagArticoloDBDao(tagArticoloDBDaoConfig, this);
        attachmentArticoloDBDao = new AttachmentArticoloDBDao(attachmentArticoloDBDaoConfig, this);

        registerDao(CacheFileDB.class, cacheFileDBDao);
        registerDao(TimetableDB.class, timetableDBDao);
        registerDao(ArticoloDB.class, articoloDBDao);
        registerDao(TagArticoloDB.class, tagArticoloDBDao);
        registerDao(AttachmentArticoloDB.class, attachmentArticoloDBDao);
    }
    
    public void clear() {
        cacheFileDBDaoConfig.clearIdentityScope();
        timetableDBDaoConfig.clearIdentityScope();
        articoloDBDaoConfig.clearIdentityScope();
        tagArticoloDBDaoConfig.clearIdentityScope();
        attachmentArticoloDBDaoConfig.clearIdentityScope();
    }

    public CacheFileDBDao getCacheFileDBDao() {
        return cacheFileDBDao;
    }

    public TimetableDBDao getTimetableDBDao() {
        return timetableDBDao;
    }

    public ArticoloDBDao getArticoloDBDao() {
        return articoloDBDao;
    }

    public TagArticoloDBDao getTagArticoloDBDao() {
        return tagArticoloDBDao;
    }

    public AttachmentArticoloDBDao getAttachmentArticoloDBDao() {
        return attachmentArticoloDBDao;
    }

}
