package it.gov.scuolesuperioridizagarolo.dao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "NEWS_DB".
 */
@Entity
public class NewsDB {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String titolo;

    @NotNull
    private String link;

    @NotNull
    private java.util.Date pubDate;

    @NotNull
    private String testo;
    private String contenuto;
    private String fullimageLink;
    private String thumbimageLink;

    @NotNull
    private String key;
    private boolean flagContenutoLetto;

    @NotNull
    private java.util.Date dataInserimento;
    private long token;

    @Generated
    public NewsDB() {
    }

    public NewsDB(Long id) {
        this.id = id;
    }

    @Generated
    public NewsDB(Long id, String titolo, String link, java.util.Date pubDate, String testo, String contenuto, String fullimageLink, String thumbimageLink, String key, boolean flagContenutoLetto, java.util.Date dataInserimento, long token) {
        this.id = id;
        this.titolo = titolo;
        this.link = link;
        this.pubDate = pubDate;
        this.testo = testo;
        this.contenuto = contenuto;
        this.fullimageLink = fullimageLink;
        this.thumbimageLink = thumbimageLink;
        this.key = key;
        this.flagContenutoLetto = flagContenutoLetto;
        this.dataInserimento = dataInserimento;
        this.token = token;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getTitolo() {
        return titolo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitolo(@NotNull String titolo) {
        this.titolo = titolo;
    }

    @NotNull
    public String getLink() {
        return link;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLink(@NotNull String link) {
        this.link = link;
    }

    @NotNull
    public java.util.Date getPubDate() {
        return pubDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPubDate(@NotNull java.util.Date pubDate) {
        this.pubDate = pubDate;
    }

    @NotNull
    public String getTesto() {
        return testo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTesto(@NotNull String testo) {
        this.testo = testo;
    }

    public String getContenuto() {
        return contenuto;
    }

    public void setContenuto(String contenuto) {
        this.contenuto = contenuto;
    }

    public String getFullimageLink() {
        return fullimageLink;
    }

    public void setFullimageLink(String fullimageLink) {
        this.fullimageLink = fullimageLink;
    }

    public String getThumbimageLink() {
        return thumbimageLink;
    }

    public void setThumbimageLink(String thumbimageLink) {
        this.thumbimageLink = thumbimageLink;
    }

    @NotNull
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(@NotNull String key) {
        this.key = key;
    }

    public boolean getFlagContenutoLetto() {
        return flagContenutoLetto;
    }

    public void setFlagContenutoLetto(boolean flagContenutoLetto) {
        this.flagContenutoLetto = flagContenutoLetto;
    }

    @NotNull
    public java.util.Date getDataInserimento() {
        return dataInserimento;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDataInserimento(@NotNull java.util.Date dataInserimento) {
        this.dataInserimento = dataInserimento;
    }

    public long getToken() {
        return token;
    }

    public void setToken(long token) {
        this.token = token;
    }

}
