package it.gov.scuolesuperioridizagarolo.dao;

import org.greenrobot.greendao.annotation.*;

import it.gov.scuolesuperioridizagarolo.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TAG_ARTICOLO_DB".
 */
@Entity(active = true)
public class TagArticoloDB {

    @Id
    private Long id;

    @NotNull
    private String tag;

    @Index
    private int remoteTagId;

    @NotNull
    private java.util.Date insertTimestamp;

    @Index
    private long fk_articleId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient TagArticoloDBDao myDao;

    @ToOne(joinProperty = "fk_articleId")
    private ArticoloDB articoloDB;

    @Generated
    private transient Long articoloDB__resolvedKey;

    @Generated
    public TagArticoloDB() {
    }

    public TagArticoloDB(Long id) {
        this.id = id;
    }

    @Generated
    public TagArticoloDB(Long id, String tag, int remoteTagId, java.util.Date insertTimestamp, long fk_articleId) {
        this.id = id;
        this.tag = tag;
        this.remoteTagId = remoteTagId;
        this.insertTimestamp = insertTimestamp;
        this.fk_articleId = fk_articleId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTagArticoloDBDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getTag() {
        return tag;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTag(@NotNull String tag) {
        this.tag = tag;
    }

    public int getRemoteTagId() {
        return remoteTagId;
    }

    public void setRemoteTagId(int remoteTagId) {
        this.remoteTagId = remoteTagId;
    }

    @NotNull
    public java.util.Date getInsertTimestamp() {
        return insertTimestamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInsertTimestamp(@NotNull java.util.Date insertTimestamp) {
        this.insertTimestamp = insertTimestamp;
    }

    public long getFk_articleId() {
        return fk_articleId;
    }

    public void setFk_articleId(long fk_articleId) {
        this.fk_articleId = fk_articleId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public ArticoloDB getArticoloDB() {
        long __key = this.fk_articleId;
        if (articoloDB__resolvedKey == null || !articoloDB__resolvedKey.equals(__key)) {
            __throwIfDetached();
            ArticoloDBDao targetDao = daoSession.getArticoloDBDao();
            ArticoloDB articoloDBNew = targetDao.load(__key);
            synchronized (this) {
                articoloDB = articoloDBNew;
            	articoloDB__resolvedKey = __key;
            }
        }
        return articoloDB;
    }

    @Generated
    public void setArticoloDB(ArticoloDB articoloDB) {
        if (articoloDB == null) {
            throw new DaoException("To-one property 'fk_articleId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.articoloDB = articoloDB;
            fk_articleId = articoloDB.getId();
            articoloDB__resolvedKey = fk_articleId;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
