package it.gov.scuolesuperioridizagarolo.dao;

import org.greenrobot.greendao.annotation.*;

import it.gov.scuolesuperioridizagarolo.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TAG_ARTICOLO_DB".
 */
@Entity(active = true)
public class TagArticoloDB {

    @Id
    private Long id;
    private String title;

    @Unique
    private Integer remoteId;
    private java.util.Date insertTimestamp;

    @Index
    private Long fk_articleId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient TagArticoloDBDao myDao;

    @ToOne(joinProperty = "fk_articleId")
    private ArticoloDB articoloDB;

    @Generated
    private transient Long articoloDB__resolvedKey;

    @Generated
    public TagArticoloDB() {
    }

    public TagArticoloDB(Long id) {
        this.id = id;
    }

    @Generated
    public TagArticoloDB(Long id, String title, Integer remoteId, java.util.Date insertTimestamp, Long fk_articleId) {
        this.id = id;
        this.title = title;
        this.remoteId = remoteId;
        this.insertTimestamp = insertTimestamp;
        this.fk_articleId = fk_articleId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTagArticoloDBDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getRemoteId() {
        return remoteId;
    }

    public void setRemoteId(Integer remoteId) {
        this.remoteId = remoteId;
    }

    public java.util.Date getInsertTimestamp() {
        return insertTimestamp;
    }

    public void setInsertTimestamp(java.util.Date insertTimestamp) {
        this.insertTimestamp = insertTimestamp;
    }

    public Long getFk_articleId() {
        return fk_articleId;
    }

    public void setFk_articleId(Long fk_articleId) {
        this.fk_articleId = fk_articleId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public ArticoloDB getArticoloDB() {
        Long __key = this.fk_articleId;
        if (articoloDB__resolvedKey == null || !articoloDB__resolvedKey.equals(__key)) {
            __throwIfDetached();
            ArticoloDBDao targetDao = daoSession.getArticoloDBDao();
            ArticoloDB articoloDBNew = targetDao.load(__key);
            synchronized (this) {
                articoloDB = articoloDBNew;
            	articoloDB__resolvedKey = __key;
            }
        }
        return articoloDB;
    }

    @Generated
    public void setArticoloDB(ArticoloDB articoloDB) {
        synchronized (this) {
            this.articoloDB = articoloDB;
            fk_articleId = articoloDB == null ? null : articoloDB.getId();
            articoloDB__resolvedKey = fk_articleId;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
