package it.gov.scuolesuperioridizagarolo.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TERMINE_DB".
*/
public class TermineDBDao extends AbstractDao<TermineDB, Long> {

    public static final String TABLENAME = "TERMINE_DB";

    /**
     * Properties of entity TermineDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Termine = new Property(1, String.class, "termine", false, "TERMINE");
        public final static Property Radice = new Property(2, String.class, "radice", false, "RADICE");
    }


    public TermineDBDao(DaoConfig config) {
        super(config);
    }
    
    public TermineDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TERMINE_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TERMINE\" TEXT NOT NULL UNIQUE ," + // 1: termine
                "\"RADICE\" TEXT NOT NULL );"); // 2: radice
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_TERMINE_DB_TERMINE ON \"TERMINE_DB\"" +
                " (\"TERMINE\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TERMINE_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TermineDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTermine());
        stmt.bindString(3, entity.getRadice());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TermineDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTermine());
        stmt.bindString(3, entity.getRadice());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TermineDB readEntity(Cursor cursor, int offset) {
        TermineDB entity = new TermineDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // termine
            cursor.getString(offset + 2) // radice
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TermineDB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTermine(cursor.getString(offset + 1));
        entity.setRadice(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TermineDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TermineDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TermineDB entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
