package it.gov.scuolesuperioridizagarolo.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TERMINE_DB".
 */
@Entity
public class TermineDB {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    @Unique
    @Index
    private String termine;

    @NotNull
    private String radice;

    @Generated
    public TermineDB() {
    }

    public TermineDB(Long id) {
        this.id = id;
    }

    @Generated
    public TermineDB(Long id, String termine, String radice) {
        this.id = id;
        this.termine = termine;
        this.radice = radice;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getTermine() {
        return termine;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTermine(@NotNull String termine) {
        this.termine = termine;
    }

    @NotNull
    public String getRadice() {
        return radice;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRadice(@NotNull String radice) {
        this.radice = radice;
    }

}
