package it.gov.scuolesuperioridizagarolo.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TIMETABLE_DB".
 */
@Entity
public class TimetableDB {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    @Unique
    @Index
    private String url;

    @Unique
    @Index
    private long remoteId;

    @NotNull
    @Unique
    @Index
    private java.util.Date createDate;

    @NotNull
    @Unique
    @Index
    private String filename;

    @NotNull
    private java.util.Date startDate;

    @NotNull
    private java.util.Date endDate;

    @NotNull
    private byte[] data;

    @Generated
    public TimetableDB() {
    }

    public TimetableDB(Long id) {
        this.id = id;
    }

    @Generated
    public TimetableDB(Long id, String url, long remoteId, java.util.Date createDate, String filename, java.util.Date startDate, java.util.Date endDate, byte[] data) {
        this.id = id;
        this.url = url;
        this.remoteId = remoteId;
        this.createDate = createDate;
        this.filename = filename;
        this.startDate = startDate;
        this.endDate = endDate;
        this.data = data;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    public long getRemoteId() {
        return remoteId;
    }

    public void setRemoteId(long remoteId) {
        this.remoteId = remoteId;
    }

    @NotNull
    public java.util.Date getCreateDate() {
        return createDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreateDate(@NotNull java.util.Date createDate) {
        this.createDate = createDate;
    }

    @NotNull
    public String getFilename() {
        return filename;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFilename(@NotNull String filename) {
        this.filename = filename;
    }

    @NotNull
    public java.util.Date getStartDate() {
        return startDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartDate(@NotNull java.util.Date startDate) {
        this.startDate = startDate;
    }

    @NotNull
    public java.util.Date getEndDate() {
        return endDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEndDate(@NotNull java.util.Date endDate) {
        this.endDate = endDate;
    }

    @NotNull
    public byte[] getData() {
        return data;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setData(@NotNull byte[] data) {
        this.data = data;
    }

}
