package it.gov.scuolesuperioridizagarolo.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TIMETABLE_DB".
 */
@Entity
public class TimetableDB {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    @Unique
    @Index
    private String url;

    @NotNull
    private String filename;

    @NotNull
    private java.util.Date start_date;

    @NotNull
    private java.util.Date end_date;

    @NotNull
    private byte[] zip_file;

    @Generated
    public TimetableDB() {
    }

    public TimetableDB(Long id) {
        this.id = id;
    }

    @Generated
    public TimetableDB(Long id, String url, String filename, java.util.Date start_date, java.util.Date end_date, byte[] zip_file) {
        this.id = id;
        this.url = url;
        this.filename = filename;
        this.start_date = start_date;
        this.end_date = end_date;
        this.zip_file = zip_file;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    @NotNull
    public String getFilename() {
        return filename;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFilename(@NotNull String filename) {
        this.filename = filename;
    }

    @NotNull
    public java.util.Date getStart_date() {
        return start_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStart_date(@NotNull java.util.Date start_date) {
        this.start_date = start_date;
    }

    @NotNull
    public java.util.Date getEnd_date() {
        return end_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEnd_date(@NotNull java.util.Date end_date) {
        this.end_date = end_date;
    }

    @NotNull
    public byte[] getZip_file() {
        return zip_file;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setZip_file(@NotNull byte[] zip_file) {
        this.zip_file = zip_file;
    }

}
