package it.gov.scuolesuperioridizagarolo.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TIMETABLE_DB".
*/
public class TimetableDBDao extends AbstractDao<TimetableDB, Long> {

    public static final String TABLENAME = "TIMETABLE_DB";

    /**
     * Properties of entity TimetableDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Url = new Property(1, String.class, "url", false, "URL");
        public final static Property Timestamp = new Property(2, int.class, "timestamp", false, "TIMESTAMP");
        public final static Property Filename = new Property(3, String.class, "filename", false, "FILENAME");
        public final static Property Start_date = new Property(4, java.util.Date.class, "start_date", false, "START_DATE");
        public final static Property End_date = new Property(5, java.util.Date.class, "end_date", false, "END_DATE");
        public final static Property Filedata = new Property(6, byte[].class, "filedata", false, "FILEDATA");
    }


    public TimetableDBDao(DaoConfig config) {
        super(config);
    }
    
    public TimetableDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TIMETABLE_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"URL\" TEXT NOT NULL UNIQUE ," + // 1: url
                "\"TIMESTAMP\" INTEGER NOT NULL UNIQUE ," + // 2: timestamp
                "\"FILENAME\" TEXT NOT NULL UNIQUE ," + // 3: filename
                "\"START_DATE\" INTEGER NOT NULL ," + // 4: start_date
                "\"END_DATE\" INTEGER NOT NULL ," + // 5: end_date
                "\"FILEDATA\" BLOB NOT NULL );"); // 6: filedata
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_TIMETABLE_DB_URL ON \"TIMETABLE_DB\"" +
                " (\"URL\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_TIMETABLE_DB_TIMESTAMP ON \"TIMETABLE_DB\"" +
                " (\"TIMESTAMP\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_TIMETABLE_DB_FILENAME ON \"TIMETABLE_DB\"" +
                " (\"FILENAME\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TIMETABLE_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TimetableDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUrl());
        stmt.bindLong(3, entity.getTimestamp());
        stmt.bindString(4, entity.getFilename());
        stmt.bindLong(5, entity.getStart_date().getTime());
        stmt.bindLong(6, entity.getEnd_date().getTime());
        stmt.bindBlob(7, entity.getFiledata());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TimetableDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUrl());
        stmt.bindLong(3, entity.getTimestamp());
        stmt.bindString(4, entity.getFilename());
        stmt.bindLong(5, entity.getStart_date().getTime());
        stmt.bindLong(6, entity.getEnd_date().getTime());
        stmt.bindBlob(7, entity.getFiledata());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TimetableDB readEntity(Cursor cursor, int offset) {
        TimetableDB entity = new TimetableDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // url
            cursor.getInt(offset + 2), // timestamp
            cursor.getString(offset + 3), // filename
            new java.util.Date(cursor.getLong(offset + 4)), // start_date
            new java.util.Date(cursor.getLong(offset + 5)), // end_date
            cursor.getBlob(offset + 6) // filedata
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TimetableDB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUrl(cursor.getString(offset + 1));
        entity.setTimestamp(cursor.getInt(offset + 2));
        entity.setFilename(cursor.getString(offset + 3));
        entity.setStart_date(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setEnd_date(new java.util.Date(cursor.getLong(offset + 5)));
        entity.setFiledata(cursor.getBlob(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TimetableDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TimetableDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TimetableDB entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
