package utility.didattica_online.tinkerCAD;

// Generated by Selenium IDE

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import javax.swing.*;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class NuovoTest {

    public static void main(String[] args) throws InterruptedException {
        WebDriver driver;
        Map<String, Object> vars;
        JavascriptExecutor js;
        JFrame f = new JFrame();
        f.setVisible(true);
        f.setAlwaysOnTop(true);
        System.setProperty("webdriver.chrome.driver", "/Users/stefano/DATA-EXT/seleniumdriver/chromedriver");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.manage().timeouts().pageLoadTimeout(30, TimeUnit.SECONDS);
        driver.manage().timeouts().setScriptTimeout(30, TimeUnit.SECONDS);
        driver.get("https://www.tinkercad.com/auth/shadowbox_register_fullscreen?next=%2F");
        driver.manage().window().setSize(new Dimension(1238, 1177));
        JOptionPane.showMessageDialog(f, "Attendere schermata regione");
        driver.findElement(By.id("Country")).click();
        {
            WebElement dropdown = driver.findElement(By.id("Country"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("DateOfBirth_custMonth")).click();
        {
            WebElement dropdown = driver.findElement(By.id("DateOfBirth_custMonth"));
            dropdown.findElement(By.xpath("//option[. = 'marzo']")).click();
        }
        driver.findElement(By.id("DateOfBirth_custDay")).click();
        {
            WebElement dropdown = driver.findElement(By.id("DateOfBirth_custDay"));
            dropdown.findElement(By.xpath("//option[. = '7']")).click();
        }
        driver.findElement(By.id("DateOfBirth_custYear")).click();
        {
            WebElement dropdown = driver.findElement(By.id("DateOfBirth_custYear"));
            dropdown.findElement(By.xpath("//option[. = '1990']")).click();
        }
        driver.findElement(By.cssSelector(".button-text")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".button-text"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }

        JOptionPane.showMessageDialog(f, "Attendere schermata email");
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("Email")).click();
        driver.findElement(By.id("Email")).sendKeys("studente01@scuolesuperioridizagarolo.edu.it");
        driver.findElement(By.id("Password")).sendKeys("Liceo123");
        driver.findElement(By.id("privacypolicy_checkbox")).click();
        driver.findElement(By.id("btnSubmit")).click();
        driver.quit();
        System.exit(0);

    }
}
