#!/bin/sh
JAR="/Users/stefano/DATA-EXT/dev-tools/javacc/javacc-6.0/bin/lib/javacc.jar"

case "`uname`" in
     CYGWIN*) JAR="`cygpath --windows -- "$JAR"`" ;;
esac

java -classpath "$JAR" javacc WordParser.jj

